services:
  postgres:
    container_name: za-postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "51234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  golang-fiber-server:
    container_name: za-fiber-api
    build:
      context: ..
      dockerfile: infra/Dockerfile
    depends_on:
      - postgres
    ports:
      - "33333:3333"
    env_file:
      - .env

volumes:
  postgres_data:
